sudo: required

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - nvm install 8

install:
  - npm install -g ganache-cli
  - composer install

notifications:
  email:
    recipients:
      - olegabrosimovnsk@gmail.com
    on_success: always
    on_failure: always

script:
  - scripts/test.sh

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 41cd0a5b-dd8e-446c-b1cc-c79ca657790c
